version: '3.8'

services:

    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db
    db:
        image: postgres
        container_name: postgres
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: task-management
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password

    # Application Service
    app:
        container_name: task-management
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        ports:
            - "5050:80"
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: issam@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
